.TH ACCSUM 1
.SH NAME
accsum \- combines character accuracy reports
.SH SYNOPSIS
.B accsum
accuracy_report1 accuracy_report2 ... >accuracy_report
.SH DESCRIPTION
.I Accsum
combines two or more character accuracy reports and writes an aggregate report
to stdout.  The input reports must have been produced by either
.I accuracy
or
.IR accsum .
.SH "SEE ALSO"
.IR accuracy (1),
.IR editopsum (1)
and
.IR wordaccsum (1).
