.TH WORDACCSUM 1
.SH NAME
wordaccsum \- combines word accuracy reports
.SH SYNOPSIS
.B wordaccsum
wordacc_report1 wordacc_report2 ... >wordacc_report
.SH DESCRIPTION
.I Wordaccsum
combines two or more word accuracy reports and writes an aggregate report
to stdout.  The input reports must have been produced by either
.I wordacc
or
.IR wordaccsum .
.SH "SEE ALSO"
.IR accsum (1),
.IR editopsum (1),
.IR nonstopacc (1)
and
.IR wordacc (1).
