.TH ACCDIST 1
.SH NAME
accdist \- displays the distribution of character accuracies
.SH SYNOPSIS
.B accdist
accuracy_report1 accuracy_report2 ... >xyfile
.SH DESCRIPTION
.I Accdist
writes to stdout the distribution of character accuracies found in the input
reports.  For
.I X
= 0 to 100, the percentage of characters recognized with at least
.IR X %
accuracy is reported.
.SH "SEE ALSO"
.IR accuracy (1)
and
.IR wordaccdist (1).

