.TH WORDACCDIST 1
.SH NAME
wordaccdist \- displays the distribution of word accuracies
.SH SYNOPSIS
.B wordaccdist
wordacc_report1 wordacc_report2 ... >xyfile
.SH DESCRIPTION
.I Wordaccdist
writes to stdout the distribution of word accuracies found in the input
reports.  For
.I X
= 0 to 100, the percentage of words recognized with at least
.IR X %
accuracy is reported.
.SH "SEE ALSO"
.IR accdist (1)
and
.IR wordacc (1).

