.TH WORDFREQ 1
.SH NAME
wordfreq \- determines the frequency of words
.SH SYNOPSIS
.B wordfreq
textfile1 textfile2 ... >resultfile
.SH DESCRIPTION
.I Wordfreq
reads one or more text files and writes to stdout the number of occurrences of
each distinct word found in these files, where a word is defined to be any
sequence of one or more letters.
.SH "SEE ALSO"
.IR ngram (1).
